#
# Copyright (c) 2024, Auterion AG
# All rights reserved.
#

# Dockerfile for a build environment to build Debian packages

ARG ROS2_DISTRO=humble
ARG UBUNTU_DISTRO=jammy

FROM ros:${ROS2_DISTRO}-ros-base-${UBUNTU_DISTRO}

# Re-request ARGs to make them available in this stage
ARG ROS2_DISTRO

# Since Foxy is EOL, we need to replace the apt keys in the image
RUN if [ "$ROS2_DISTRO" = "foxy" ]; then \
      echo "Warning: Replacing ros2 apt keys for foxy." && \
      rm -f /etc/apt/sources.list.d/ros2* && \
      apt-get update && apt-get install -y curl gnupg && \
      curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg && \
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" > /etc/apt/sources.list.d/ros2.list; \
    fi

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4B63CF8FDE49746E98FA01DDAD19BAB3CBF125EA
RUN apt-get update && apt-get install -y \
    dh-make \
    python3-bloom \
    python3-rosdep \
    fakeroot \
    dh-python

# Add auterion cloudsmith
RUN curl -1sLf \
  'https://dl.cloudsmith.io/public/auterion/public/setup.deb.sh' \
  | bash

COPY /scripts /scripts
WORKDIR /work

CMD [ "/ros_entrypoint.sh", "/scripts/build_package.sh" ]
